# Site settings
title: Jonathan Reyes
description: Learn a little bit about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonathanreyes.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jonathan Reyes
user_description: I'm a nomad Hardware Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT.. I'm one of the two guys behind all the JS related stuff. Visit my blog here":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Physical Design Engineer
email: jmr533@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
